---
exp_name: generate_dummy_articles # 0417
root_dir: /home/jovyan/llm_risk_management/src
save_dir: data/dummy_articles
device: 'cpu' # 'mps' in M1 Mac

model_name: tiiuae/falcon-40b # meta-llama/Llama-2-7b-h
task: text-generation
topics: [
    {"category": "Travel", "keyword": "Exotic Destinations"},
    {"category": "Health and Wellness", "keyword": "Mindfulness Techniques"},
    {"category": "Technology", "keyword": "Artificial Intelligence in Healthcare"},
    {"category": "Science", "keyword": "Space Exploration"},
    {"category": "Food and Cooking", "keyword": "Plant-Based Recipes"},
    {"category": "Literature", "keyword": "Classic Novels"},
    {"category": "Personal Development", "keyword": "Goal Setting"},
    {"category": "Entertainment", "keyword": "Upcoming Movies 2023"},
    {"category": "Environmental Issues", "keyword": "Plastic Pollution"},
    {"category": "Art and Creativity", "keyword": "Street Art Movement"}
]
